# Generated by Django 5.2.8 on 2025-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.ImageField(choices=[(4, '4 Weeks'), (6, '6 Weeks'), (8, '8 Weeks'), (12, '12 Weeks')], upload_to=''),
        ),
    ]
