# Generated by Django 5.2.8 on 2025-11-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[(4, '4 Weeks'), (6, '6 Weeks'), (8, '8 Weeks'), (12, '12 Weeks')]),
        ),
    ]
