# Generated by Django 5.2.8 on 2025-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_trainer_alter_course_duration_student_course_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(upload_to='courses'),
        ),
    ]
