# Generated by Django 5.2.8 on 2025-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(upload_to='trainer'),
        ),
    ]
