# Generated by Django 5.2.8 on 2025-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_trainer_trainer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
    ]
